language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t oleg/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true oleg/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "docker-react"
  env: "Dockerreact-env"
  bucker_name: "elasticbeanstalk-us-east-2-406161336913"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
